/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:d4d6fff1-8a18-4a37-a7e7-489037182b64",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_3540ibu49",
    "aws_user_pools_web_client_id": "1ol5aedb19cqvk81q1aiqci9vo",
    "oauth": {
        "domain": "bandtrackerfrontenddd6af60f-dd6af60f-dev.auth.us-east-2.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "http://localhost:3000/",
        "redirectSignOut": "http://localhost:3000/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS"
};


export default awsmobile;
